services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Connectors\PhoenixHttpClient:
        arguments:
            $baseUrl: '%env(PHOENIX_BASE_URL)%'

    App\Connectors\PhoenixClient: '@App\Connectors\PhoenixHttpClient'

    App\Utils\CurrentTimeProvider: '@App\Utils\SystemTimeProvider'